version: "3.8"
services:
  api-temanhewan:
    container_name: api-temanhewan
    image: dptsi/laravel-web-dev
    volumes:
      - ./src:/var/www/html
    env_file: .env
    dns:
      - 1.1.1.1
      - 1.0.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
