version: "3.8"

services:
  temanhewan-api:
    image: mirzaq19/temanhewan-api:latest
    container_name: temanhewan-api
    volumes:
      - ./src:/var/www/html
    env_file: .env
    dns:
      - 1.1.1.1
      - 1.0.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginx-proxy-network
      - temanhewan-network

  temanhewan-db:
    image: mariadb:latest
    container_name: temanhewan-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - temanhewandb:/var/lib/mysql
    env_file: db.env
    networks:
      - temanhewan-network

  temanhewan-phpmyadmin:
    image: phpmyadmin:latest
    container_name: temanhewan-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    env_file: pma.env
    networks:
      - temanhewan-network

networks:
  nginx-proxy-network:
    external: true
  temanhewan-network:
    driver: bridge

volumes:
  temanhewandb: